// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type STV struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ballots           []*Ballot              `protobuf:"bytes,1,rep,name=ballots,proto3" json:"ballots,omitempty"`
	Candidates        []*Candidate           `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Elections         []*Election            `protobuf:"bytes,3,rep,name=elections,proto3" json:"elections,omitempty"`
	Urls              []*URL                 `protobuf:"bytes,4,rep,name=urls,proto3" json:"urls,omitempty"`
	Voters            []*Voter               `protobuf:"bytes,5,rep,name=voters,proto3" json:"voters,omitempty"`
	AllowRegistration bool                   `protobuf:"varint,6,opt,name=allowRegistration,proto3" json:"allowRegistration,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *STV) Reset() {
	*x = STV{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *STV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STV) ProtoMessage() {}

func (x *STV) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STV.ProtoReflect.Descriptor instead.
func (*STV) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *STV) GetBallots() []*Ballot {
	if x != nil {
		return x.Ballots
	}
	return nil
}

func (x *STV) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *STV) GetElections() []*Election {
	if x != nil {
		return x.Elections
	}
	return nil
}

func (x *STV) GetUrls() []*URL {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *STV) GetVoters() []*Voter {
	if x != nil {
		return x.Voters
	}
	return nil
}

func (x *STV) GetAllowRegistration() bool {
	if x != nil {
		return x.AllowRegistration
	}
	return false
}

type Ballot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Election      string                 `protobuf:"bytes,2,opt,name=election,proto3" json:"election,omitempty"`
	Choice        map[uint64]string      `protobuf:"bytes,3,rep,name=choice,proto3" json:"choice,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map[order, candidate id]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ballot) Reset() {
	*x = Ballot{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ballot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ballot) ProtoMessage() {}

func (x *Ballot) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ballot.ProtoReflect.Descriptor instead.
func (*Ballot) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *Ballot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ballot) GetElection() string {
	if x != nil {
		return x.Election
	}
	return ""
}

func (x *Ballot) GetChoice() map[uint64]string {
	if x != nil {
		return x.Choice
	}
	return nil
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Election      string                 `protobuf:"bytes,2,opt,name=election,proto3" json:"election,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *Candidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Candidate) GetElection() string {
	if x != nil {
		return x.Election
	}
	return ""
}

func (x *Candidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Election struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Ron           bool                   `protobuf:"varint,4,opt,name=ron,proto3" json:"ron,omitempty"`
	Seats         uint64                 `protobuf:"varint,5,opt,name=seats,proto3" json:"seats,omitempty"`
	Open          bool                   `protobuf:"varint,6,opt,name=open,proto3" json:"open,omitempty"`
	Closed        bool                   `protobuf:"varint,7,opt,name=closed,proto3" json:"closed,omitempty"`
	Result        *Result                `protobuf:"bytes,8,opt,name=result,proto3" json:"result,omitempty"`
	Excluded      []*Voter               `protobuf:"bytes,9,rep,name=excluded,proto3" json:"excluded,omitempty"`
	Voters        uint64                 `protobuf:"varint,10,opt,name=voters,proto3" json:"voters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Election) Reset() {
	*x = Election{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Election) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Election) ProtoMessage() {}

func (x *Election) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Election.ProtoReflect.Descriptor instead.
func (*Election) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *Election) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Election) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Election) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Election) GetRon() bool {
	if x != nil {
		return x.Ron
	}
	return false
}

func (x *Election) GetSeats() uint64 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *Election) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *Election) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *Election) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Election) GetExcluded() []*Voter {
	if x != nil {
		return x.Excluded
	}
	return nil
}

func (x *Election) GetVoters() uint64 {
	if x != nil {
		return x.Voters
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rounds        uint64                 `protobuf:"varint,1,opt,name=rounds,proto3" json:"rounds,omitempty"`
	Winners       []string               `protobuf:"bytes,2,rep,name=winners,proto3" json:"winners,omitempty"`
	Round         []*Round               `protobuf:"bytes,3,rep,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetRounds() uint64 {
	if x != nil {
		return x.Rounds
	}
	return 0
}

func (x *Result) GetWinners() []string {
	if x != nil {
		return x.Winners
	}
	return nil
}

func (x *Result) GetRound() []*Round {
	if x != nil {
		return x.Round
	}
	return nil
}

type Round struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Round           uint64                 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Blanks          uint64                 `protobuf:"varint,2,opt,name=blanks,proto3" json:"blanks,omitempty"`
	CandidateStatus []*CandidateStatus     `protobuf:"bytes,3,rep,name=candidateStatus,proto3" json:"candidateStatus,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Round) Reset() {
	*x = Round{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Round) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round) ProtoMessage() {}

func (x *Round) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round.ProtoReflect.Descriptor instead.
func (*Round) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *Round) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Round) GetBlanks() uint64 {
	if x != nil {
		return x.Blanks
	}
	return 0
}

func (x *Round) GetCandidateStatus() []*CandidateStatus {
	if x != nil {
		return x.CandidateStatus
	}
	return nil
}

type CandidateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateRank uint64                 `protobuf:"varint,1,opt,name=candidateRank,proto3" json:"candidateRank,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	NoOfVotes     float64                `protobuf:"fixed64,3,opt,name=noOfVotes,proto3" json:"noOfVotes,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateStatus) Reset() {
	*x = CandidateStatus{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateStatus) ProtoMessage() {}

func (x *CandidateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateStatus.ProtoReflect.Descriptor instead.
func (*CandidateStatus) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *CandidateStatus) GetCandidateRank() uint64 {
	if x != nil {
		return x.CandidateRank
	}
	return 0
}

func (x *CandidateStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CandidateStatus) GetNoOfVotes() float64 {
	if x != nil {
		return x.NoOfVotes
	}
	return 0
}

func (x *CandidateStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type URL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Election      string                 `protobuf:"bytes,2,opt,name=election,proto3" json:"election,omitempty"`
	Voter         string                 `protobuf:"bytes,3,opt,name=voter,proto3" json:"voter,omitempty"`
	Voted         bool                   `protobuf:"varint,4,opt,name=voted,proto3" json:"voted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URL) Reset() {
	*x = URL{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *URL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *URL) GetElection() string {
	if x != nil {
		return x.Election
	}
	return ""
}

func (x *URL) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

func (x *URL) GetVoted() bool {
	if x != nil {
		return x.Voted
	}
	return false
}

type Voter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Voter) Reset() {
	*x = Voter{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Voter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voter) ProtoMessage() {}

func (x *Voter) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voter.ProtoReflect.Descriptor instead.
func (*Voter) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

func (x *Voter) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Voter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\astorage\"\x8d\x02\n" +
	"\x03STV\x12)\n" +
	"\aballots\x18\x01 \x03(\v2\x0f.storage.BallotR\aballots\x122\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x12.storage.CandidateR\n" +
	"candidates\x12/\n" +
	"\telections\x18\x03 \x03(\v2\x11.storage.ElectionR\telections\x12 \n" +
	"\x04urls\x18\x04 \x03(\v2\f.storage.URLR\x04urls\x12&\n" +
	"\x06voters\x18\x05 \x03(\v2\x0e.storage.VoterR\x06voters\x12,\n" +
	"\x11allowRegistration\x18\x06 \x01(\bR\x11allowRegistration\"\xa4\x01\n" +
	"\x06Ballot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\belection\x18\x02 \x01(\tR\belection\x123\n" +
	"\x06choice\x18\x03 \x03(\v2\x1b.storage.Ballot.ChoiceEntryR\x06choice\x1a9\n" +
	"\vChoiceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\tCandidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\belection\x18\x02 \x01(\tR\belection\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x91\x02\n" +
	"\bElection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03ron\x18\x04 \x01(\bR\x03ron\x12\x14\n" +
	"\x05seats\x18\x05 \x01(\x04R\x05seats\x12\x12\n" +
	"\x04open\x18\x06 \x01(\bR\x04open\x12\x16\n" +
	"\x06closed\x18\a \x01(\bR\x06closed\x12'\n" +
	"\x06result\x18\b \x01(\v2\x0f.storage.ResultR\x06result\x12*\n" +
	"\bexcluded\x18\t \x03(\v2\x0e.storage.VoterR\bexcluded\x12\x16\n" +
	"\x06voters\x18\n" +
	" \x01(\x04R\x06voters\"`\n" +
	"\x06Result\x12\x16\n" +
	"\x06rounds\x18\x01 \x01(\x04R\x06rounds\x12\x18\n" +
	"\awinners\x18\x02 \x03(\tR\awinners\x12$\n" +
	"\x05round\x18\x03 \x03(\v2\x0e.storage.RoundR\x05round\"y\n" +
	"\x05Round\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x04R\x05round\x12\x16\n" +
	"\x06blanks\x18\x02 \x01(\x04R\x06blanks\x12B\n" +
	"\x0fcandidateStatus\x18\x03 \x03(\v2\x18.storage.CandidateStatusR\x0fcandidateStatus\"}\n" +
	"\x0fCandidateStatus\x12$\n" +
	"\rcandidateRank\x18\x01 \x01(\x04R\rcandidateRank\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\tnoOfVotes\x18\x03 \x01(\x01R\tnoOfVotes\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"_\n" +
	"\x03URL\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\belection\x18\x02 \x01(\tR\belection\x12\x14\n" +
	"\x05voter\x18\x03 \x01(\tR\x05voter\x12\x14\n" +
	"\x05voted\x18\x04 \x01(\bR\x05voted\"1\n" +
	"\x05Voter\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB!Z\x1fgithub.com/ystv/stv-web/storageb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_storage_proto_goTypes = []any{
	(*STV)(nil),             // 0: storage.STV
	(*Ballot)(nil),          // 1: storage.Ballot
	(*Candidate)(nil),       // 2: storage.Candidate
	(*Election)(nil),        // 3: storage.Election
	(*Result)(nil),          // 4: storage.Result
	(*Round)(nil),           // 5: storage.Round
	(*CandidateStatus)(nil), // 6: storage.CandidateStatus
	(*URL)(nil),             // 7: storage.URL
	(*Voter)(nil),           // 8: storage.Voter
	nil,                     // 9: storage.Ballot.ChoiceEntry
}
var file_storage_proto_depIdxs = []int32{
	1,  // 0: storage.STV.ballots:type_name -> storage.Ballot
	2,  // 1: storage.STV.candidates:type_name -> storage.Candidate
	3,  // 2: storage.STV.elections:type_name -> storage.Election
	7,  // 3: storage.STV.urls:type_name -> storage.URL
	8,  // 4: storage.STV.voters:type_name -> storage.Voter
	9,  // 5: storage.Ballot.choice:type_name -> storage.Ballot.ChoiceEntry
	4,  // 6: storage.Election.result:type_name -> storage.Result
	8,  // 7: storage.Election.excluded:type_name -> storage.Voter
	5,  // 8: storage.Result.round:type_name -> storage.Round
	6,  // 9: storage.Round.candidateStatus:type_name -> storage.CandidateStatus
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
